name: git actions

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: OS release
        run: cat /etc/os-release

      - name: Free memory
        run: free -h

      - name: Date now
        run: date

