---
name: git actions
  on:
    push:
      branch:
        -main 
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: os release
        run: cat /etc/osrelease
      
      - name: free memory
        run: free -h

      - name: date now
        run: date
        

